import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-around items-center h-[56px] text-[20px] font-black bg-black fixed top-0 w-full text-white">
          <Link href={"/"}>
            <p>홈</p>
          </Link>
          <Link href={"/champions"}>
            <p>챔피언</p>
          </Link>
          <Link href={"/items"}>
            <p>아이템</p>
          </Link>
          <Link href={"/rotation"}>
            <p>로테이션</p>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
